name = "cleanWitgen"
version = "0.1.0"
defaultTargets = ["Witgen"]

[[lean_lib]]
name = "Witgen"

[[lean_exe]]
name = "witgen"
root = "Main"

[[require]]
name = "caliper"
git = "https://github.com/zksecurity/caliper"
rev = "b62f7c8be35df0aa728e5a6aac7bae85eef67449"
